grid_size:
  row: 4
  col: 3
  len: 1.5
policy:
  policy_file: "/home/redwan/ros/melodic/dev/src/tase_exp/result/policy.txt"
  belief_file: "/home/redwan/ros/melodic/dev/src/tase_exp/result/belief.txt"
  test_file: "/home/redwan/ros/melodic/dev/src/tase_exp/result/corridor_test_11"
  test_folder : "/home/ar103/ros/kinetic/system/src/tase_exp/config/Data/rss2"
topic_pub:
  vicon: "/vicon/fetch/fetch"
  goal: "/fetch_move_base_planner/query_goal"
  repeat: 3
move_base:
  xy_tolarance: 0.20
  pitch: 0.62
  nap_rate: 5
